
DROP TABLE IF EXISTS PERSON;
CREATE TABLE IF NOT EXISTS PERSON(

    ID BIGINT(255) AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    AGE INT(2) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE) VALUES ('Bob', 'T', 24);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE) VALUES ('Sachin', 'Tendulkar', 45);
